ignore:
  - "**/*View.java"               # Views
  - "**/*Skin.java"               # Skins
  - "**/WorkbenchModule.java"     # Abstract class cannot be tested: Module
  - "**/View.java"                # Interface: View
  - "**/Presenter.java"           # Abstract class: Presenter
  - "**/Dialog*Content.java"      # Dialog View Controls
  - "**/PrettyScrollPane.java"    # Purely View Control
